import { ShieldCheck, ExternalLink, Landmark } from 'lucide-react';

export default function Footer() {
  return (
    <footer className="mt-10 border-t border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-950/40">
      <div className="mx-auto max-w-7xl px-4 py-6 sm:px-6">
        <div className="flex flex-col items-start justify-between gap-4 md:flex-row md:items-center">
          <div className="flex flex-wrap items-center gap-2">
            <span className="badge bg-emerald-50 text-emerald-700 dark:bg-emerald-950/60 dark:text-emerald-400">
              <ShieldCheck className="h-3.5 w-3.5" /> robots.txt honored
            </span>
            <span className="badge bg-emerald-50 text-emerald-700 dark:bg-emerald-950/60 dark:text-emerald-400">
              <ShieldCheck className="h-3.5 w-3.5" /> 5–15s rate limiting
            </span>
            <span className="badge bg-emerald-50 text-emerald-700 dark:bg-emerald-950/60 dark:text-emerald-400">
              <ShieldCheck className="h-3.5 w-3.5" /> Off-peak 02:00–04:00 IST
            </span>
            <span className="badge bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300">
              Simulation data · not for citation
            </span>
          </div>
          <div className="flex items-center gap-4 text-xs text-slate-500 dark:text-slate-400">
            <a href="https://dgca.gov.in" target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 hover:text-brand-600 dark:hover:text-brand-400">
              <Landmark className="h-3.5 w-3.5" /> DGCA traffic weights methodology
            </a>
            <a href="/api/docs" target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 hover:text-brand-600 dark:hover:text-brand-400">
              <ExternalLink className="h-3.5 w-3.5" /> API portal
            </a>
          </div>
        </div>
        <p className="mt-4 text-[11px] leading-relaxed text-slate-400 dark:text-slate-600">
          APIx prototype. Fares are generated by a deterministic simulation engine for demonstration and
          system-integration testing; figures are not official statistics. Production deployment must review
          each source portal's Terms of Service before enabling live collection. Built for MoSPI &amp; RBI
          statistical infrastructure evaluation.
        </p>
      </div>
    </footer>
  );
}
